version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1.5-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run: echo 'RUN'
        
      - store_artifacts:
          path: artifacts/
          destination: hello-world
